### ISSUE TITLE
Radiant exposure units. is it wrong?

### ISSUE THREAD

**Issue by HugoGasca** [TheBIPM/SI_Digital_Framework#5]
Hi, I am implementing digital documents about Mexico National Measurement Standards. So far so good linking to quantities and units in the digital framework. However I have the case of Radiant exposure, all the references I have defines radiant exposure as Joule/meter2, however the SIDF provides Joule meter2. Any guidance is appreciated.

**Comment by jmilesBIPM** [comment]
Yes, this should be corrected. Please can you merge the latest quantities_jrm file so I can pull the updated file?
Thanks!
________________________________

**Comment by fmeynadier** [comment]
@jmilesBIPM this should already be the case in our dev repo... please pull the latest commit from the main branch and start a new branch from there (or rebase the existing one)

**Comment by jmilesBIPM** [comment]
OK thanks. I've pushed the corrected file. Please can you merge with the main branch and regenerate the TTLs?

**Comment by fmeynadier** [comment]
Hello again, thank you @HugoGasca for reporting the bug, you should find it has been fixed in the current update (2024-11-12)
