### ISSUE TITLE
binary tree missing in the page for a unit expression 

### ISSUE THREAD

**Issue by jmilesBIPM** [TheBIPM/SI_Digital_Framework#7]
If I click on "parse expression" I obtain the binary tree correctly.

However, if I open a PID such as https://si-digital-framework.org/SI/units/kilogram.millimetre2.nanosecond-2
the binary tree is now empty:

![image](https://github.com/user-attachments/assets/85a456b9-68e0-43e4-998d-63151a6277d3)

**Comment by fmeynadier** [comment]
Solved in today's update
